"use client";

import { useEffect, useMemo, useState } from "react";

type Role = "patient" | "doctor" | "admin";
type IconName = "home" | "calendar" | "users" | "pill" | "bell" | "settings" | "search" | "clock" | "sparkle" | "shield" | "plus" | "chevron" | "activity" | "logout" | "stethoscope" | "clipboard" | "check";

const doctors = [
  { id: "dr-nila", name: "Dr. Nila Varma", specialty: "General Medicine", experience: "12 yrs", next: "10:30 AM", initials: "NV", color: "mint" },
  { id: "dr-arjun", name: "Dr. Arjun Rao", specialty: "Dermatology", experience: "9 yrs", next: "11:45 AM", initials: "AR", color: "peach" },
  { id: "dr-meera", name: "Dr. Meera Iyer", specialty: "Cardiology", experience: "15 yrs", next: "02:15 PM", initials: "MI", color: "lilac" },
];

const navigation: Record<Role, { label: string; icon: IconName }[]> = {
  patient: [{ label: "Overview", icon: "home" }, { label: "Appointments", icon: "calendar" }, { label: "Find a doctor", icon: "search" }, { label: "Medications", icon: "pill" }],
  doctor: [{ label: "Today", icon: "home" }, { label: "My schedule", icon: "calendar" }, { label: "Patient queue", icon: "users" }, { label: "Visit notes", icon: "clipboard" }],
  admin: [{ label: "Operations", icon: "activity" }, { label: "Doctors", icon: "stethoscope" }, { label: "Leave planner", icon: "calendar" }, { label: "Notifications", icon: "bell" }],
};

function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, React.ReactNode> = {
    home: <><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    pill: <><path d="m10.5 20.5 10-10a5 5 0 0 0-7-7l-10 10a5 5 0 0 0 7 7Z"/><path d="m8.5 8.5 7 7"/></>,
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1v.1h-4v-.1a1.7 1.7 0 0 0-1.1-1.6 1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1-.4h-.1v-4H3a1.7 1.7 0 0 0 1.6-1.1 1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1v-.1h4V3a1.7 1.7 0 0 0 1.1 1.6 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.12.37.34.7.6 1 .29.29.64.42 1 .4h.1v4H21a1.7 1.7 0 0 0-1.6.6Z"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    sparkle: <><path d="m12 3 1.2 3.8L17 8l-3.8 1.2L12 13l-1.2-3.8L7 8l3.8-1.2L12 3Z"/><path d="m5 14 .8 2.2L8 17l-2.2.8L5 20l-.8-2.2L2 17l2.2-.8L5 14ZM19 13l.6 1.4L21 15l-1.4.6L19 17l-.6-1.4L17 15l1.4-.6L19 13Z"/></>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>, plus: <path d="M12 5v14M5 12h14"/>, chevron: <path d="m9 18 6-6-6-6"/>, activity: <path d="M3 12h4l2-7 4 14 2-7h6"/>,
    logout: <><path d="M10 17l5-5-5-5M15 12H3"/><path d="M15 4h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4"/></>,
    stethoscope: <><path d="M6 3v5a4 4 0 0 0 8 0V3"/><path d="M8 3H4M16 3h-4M10 15v1a5 5 0 0 0 10 0v-2"/><circle cx="20" cy="11" r="2"/></>,
    clipboard: <><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4.5V3h6v1.5M9 10h6M9 14h6"/></>, check: <path d="m5 12 4 4L19 6"/>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function Avatar({ initials, tone = "mint" }: { initials: string; tone?: string }) { return <span className={`avatar ${tone}`}>{initials}</span>; }
function StatusPill({ children, tone = "green" }: { children: React.ReactNode; tone?: "green" | "orange" | "red" | "blue" | "neutral" }) { return <span className={`status-pill ${tone}`}><span className="status-dot" />{children}</span>; }

export default function ArogyaFlowApp() {
  const [role, setRole] = useState<Role>("patient");
  const [activeNav, setActiveNav] = useState("Overview");
  const [bookingOpen, setBookingOpen] = useState(false);
  const [bookingStep, setBookingStep] = useState(1);
  const [selectedDoctor, setSelectedDoctor] = useState(doctors[0]);
  const [selectedSlot, setSelectedSlot] = useState("10:30 AM");
  const [symptoms, setSymptoms] = useState("Headache since yesterday, mild fever and tiredness.");
  const [holdSeconds, setHoldSeconds] = useState(120);
  const [booked, setBooked] = useState(false);
  const [leaveImpact, setLeaveImpact] = useState(false);
  const [summaryReady, setSummaryReady] = useState(false);
  useEffect(() => { if (!bookingOpen || bookingStep !== 2 || holdSeconds <= 0) return; const timer = window.setInterval(() => setHoldSeconds((value) => Math.max(value - 1, 0)), 1000); return () => window.clearInterval(timer); }, [bookingOpen, bookingStep, holdSeconds]);
  const holdLabel = useMemo(() => `${Math.floor(holdSeconds / 60)}:${String(holdSeconds % 60).padStart(2, "0")}`, [holdSeconds]);
  const beginBooking = () => { setBookingStep(1); setHoldSeconds(120); setBooked(false); setBookingOpen(true); };
  const switchRole = (nextRole: Role) => { setRole(nextRole); setActiveNav(navigation[nextRole][0].label); };
  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><span /></span><span>ArogyaFlow</span></div>
      <div className="profile-block"><Avatar initials={role === "patient" ? "AK" : role === "doctor" ? "NV" : "OP"} tone={role === "admin" ? "peach" : "mint"}/><div><strong>{role === "patient" ? "Ananya Krish" : role === "doctor" ? "Dr. Nila Varma" : "Clinic Ops"}</strong><span>{role[0].toUpperCase() + role.slice(1)} portal</span></div></div>
      <nav className="side-nav" aria-label={`${role} navigation`}>{navigation[role].map((item) => <button key={item.label} className={activeNav === item.label ? "active" : ""} onClick={() => setActiveNav(item.label)}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav>
      <div className="sidebar-foot"><button><Icon name="settings"/>Settings</button><button><Icon name="logout"/>Log out</button><div className="privacy-note"><Icon name="shield" size={16}/><span>Sample data only<br/><small>Nothing here is a real patient record</small></span></div></div>
    </aside>
    <section className="workspace">
      <header className="topbar"><div className="mobile-brand"><span className="brand-mark"><span/></span>ArogyaFlow</div><div className="searchbox"><Icon name="search"/><input aria-label="Search" placeholder={role === "patient" ? "Search doctors or appointments…" : "Search patients or records…"}/></div><div className="top-actions"><span className="demo-badge">Demo mode · sample patient data</span><button className="icon-button" aria-label="Notifications"><Icon name="bell"/><span className="notification-dot"/></button><Avatar initials="AK"/></div></header>
      <div className="mobile-role-switch" aria-label="Preview role">{(["patient", "doctor", "admin"] as Role[]).map((item) => <button key={item} className={role === item ? "active" : ""} onClick={() => switchRole(item)}>{item}</button>)}</div>
      <div className="page-content"><div className="page-heading"><div><p className="eyebrow">{role === "patient" ? "Saturday, 22 August" : role === "doctor" ? "Today at the clinic" : "Clinic overview"}</p><h1>{role === "patient" ? "Good afternoon, Ananya" : role === "doctor" ? "Here’s what your day looks like" : "The clinic is running smoothly"}</h1><p>{role === "patient" ? "Hope you’re feeling okay today. Here’s what’s coming up." : role === "doctor" ? "Patient notes are ready, so you can spend less time catching up." : "Appointments and reminders are up to date."}</p></div><div className="role-switcher"><span>See the app as</span><div>{(["patient", "doctor", "admin"] as Role[]).map((item) => <button key={item} className={role === item ? "active" : ""} onClick={() => switchRole(item)}>{item}</button>)}</div></div></div>
        {role === "patient" && <PatientDashboard onBook={beginBooking} booked={booked}/>} {role === "doctor" && <DoctorDashboard summaryReady={summaryReady} onSummary={() => setSummaryReady(true)}/>} {role === "admin" && <AdminDashboard leaveImpact={leaveImpact} onLeave={() => setLeaveImpact(true)}/>} 
      </div>
    </section>
    {bookingOpen && <BookingPanel step={bookingStep} setStep={setBookingStep} onClose={() => setBookingOpen(false)} selectedDoctor={selectedDoctor} setSelectedDoctor={setSelectedDoctor} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} symptoms={symptoms} setSymptoms={setSymptoms} holdLabel={holdLabel} holdExpired={holdSeconds === 0} booked={booked} onConfirm={() => { setBooked(true); setBookingStep(3); }}/>} 
  </main>;
}

function PatientDashboard({ onBook, booked }: { onBook: () => void; booked: boolean }) {
  return <>{booked && <div className="success-banner"><span><Icon name="check"/></span><div><strong>You’re booked!</strong><p>We’ll send the details to you and your doctor and add the visit to both calendars.</p></div></div>}
    <section className="patient-grid"><article className="card next-card"><div className="card-head"><div><span className="section-kicker">Next appointment</span><h2>General consultation</h2></div><StatusPill>Confirmed</StatusPill></div><div className="appointment-person"><Avatar initials="NV"/><div><strong>Dr. Nila Varma</strong><span>General Medicine · 12 years</span></div></div><div className="appointment-meta"><div><Icon name="calendar"/><span><small>Date</small><strong>Mon, 24 Aug</strong></span></div><div><Icon name="clock"/><span><small>Time</small><strong>10:30 – 11:00 AM</strong></span></div></div><div className="visit-prep"><span><Icon name="sparkle" size={16}/></span><div><strong>Your note for Dr. Nila is ready</strong><p>She can read it before your visit, and you can still make changes.</p></div><button aria-label="Open your note for the doctor"><Icon name="chevron"/></button></div><div className="card-actions"><button className="primary-button" onClick={onBook}><Icon name="plus"/>Book another</button><button className="secondary-button">Reschedule</button></div></article>
      <article className="card medication-card"><div className="card-head"><div><span className="section-kicker">A little nudge for today</span><h2>Your medicines</h2></div><button className="text-button">See schedule</button></div><div className="progress-ring"><div><strong>2<span>/3</span></strong><small>taken</small></div></div><div className="med-list"><Med done name="Vitamin D3" detail="1 tablet · after breakfast" time="8:30 AM"/><Med done name="Paracetamol" detail="500 mg · after lunch" time="1:30 PM"/><Med name="Paracetamol" detail="500 mg · after dinner" time="8:30 PM"/></div></article></section>
    <section className="card care-strip"><div className="care-title"><span className="mini-illustration"><Icon name="activity" size={24}/></span><div><span className="section-kicker">We’ll stay with you</span><h2>From booking to feeling better</h2></div></div><div className="care-flow"><Flow done n="1" title="You shared what’s wrong" detail="Today, 9:12 AM"/><i/><Flow current n="2" title="Your doctor catches up" detail="Before your visit"/><i/><Flow n="3" title="Take-home care plan" detail="After consultation"/><i/><Flow n="4" title="Gentle reminders" detail="When you need them"/></div></section>
    <section className="section-block"><div className="section-title"><div><span className="section-kicker">Available today</span><h2>Find someone who can help</h2></div><button className="text-button">See all doctors <Icon name="chevron" size={15}/></button></div><div className="doctor-grid">{doctors.map((doctor) => <article className="doctor-card" key={doctor.id}><div className="doctor-top"><Avatar initials={doctor.initials} tone={doctor.color}/><StatusPill tone="blue">Next {doctor.next}</StatusPill></div><h3>{doctor.name}</h3><p>{doctor.specialty}</p><span>{doctor.experience} experience</span><button onClick={onBook}>See available times <Icon name="chevron" size={15}/></button></article>)}</div></section>
  </>;
}

function Med({ done = false, name, detail, time }: { done?: boolean; name: string; detail: string; time: string }) { return <div className={`med-row ${done ? "done" : ""}`}><button aria-label={done ? "Taken" : "Mark as taken"}>{done && <Icon name="check"/>}</button><div><strong>{name}</strong><span>{detail}</span></div><time>{time}</time></div>; }
function Flow({ done, current, n, title, detail }: { done?: boolean; current?: boolean; n: string; title: string; detail: string }) { return <div className={done ? "complete" : current ? "current" : ""}><span>{done ? <Icon name="check" size={14}/> : n}</span><strong>{title}</strong><small>{detail}</small></div>; }

function DoctorDashboard({ summaryReady, onSummary }: { summaryReady: boolean; onSummary: () => void }) {
  const queue = [{ time: "09:30", name: "Ravi Kumar", initials: "RK", complaint: "Chest tightness after walking", urgency: "High", tone: "red" as const }, { time: "10:30", name: "Ananya Krish", initials: "AK", complaint: "Headache, fever and fatigue", urgency: "Medium", tone: "orange" as const }, { time: "11:15", name: "Fathima Ali", initials: "FA", complaint: "Routine diabetes follow-up", urgency: "Low", tone: "green" as const }];
  return <><section className="metric-grid"><Metric value="8" label="Visits today" detail="2 completed"/><Metric value="3" label="AI briefs ready" detail="1 needs review" tone="orange"/><Metric value="26 min" label="Avg. consultation" detail="On schedule"/><Metric value="100%" label="Calendar sync" detail="All up to date"/></section>
    <section className="clinical-grid"><article className="card queue-card"><div className="card-head"><div><span className="section-kicker">Prioritised safely</span><h2>Upcoming patient queue</h2></div><StatusPill>Live</StatusPill></div>{queue.map((item, index) => <button className={`queue-row ${index === 1 ? "selected" : ""}`} key={item.name}><time>{item.time}</time><Avatar initials={item.initials} tone={index === 0 ? "peach" : "mint"}/><span><strong>{item.name}</strong><small>{item.complaint}</small></span><StatusPill tone={item.tone}>{item.urgency}</StatusPill><Icon name="chevron" size={16}/></button>)}</article>
      <article className="card brief-card"><div className="card-head"><div><span className="ai-label"><Icon name="sparkle" size={14}/> AI-organised patient note</span><h2>Ananya Krish</h2></div><span className="review-badge"><Icon name="shield" size={14}/> Please check before the visit</span></div><div className="brief-section"><label>What Ananya is coming in for</label><p>Headache since yesterday with mild fever and fatigue. No reported breathing difficulty.</p></div><div className="brief-section"><label>Questions that may help</label><ol><li>Did the headache begin suddenly or gradually?</li><li>Any neck stiffness, rash, nausea, or light sensitivity?</li><li>Have you taken any medication so far?</li></ol></div><div className="source-chip">Written by Ananya in her symptom form · 64 words</div><div className="safety-callout"><strong>A starting point, not a diagnosis</strong><span>Please check the patient’s own words and use your clinical judgement.</span></div></article></section>
    <section className="card note-composer"><div><span className="section-kicker">After the visit</span><h2>Turn your notes into something patients can understand</h2><p>Write as you usually do. ArogyaFlow keeps your original note and prepares a simpler version for you to check.</p></div><textarea defaultValue="Viral fever suspected. Hydration advised. Paracetamol 500 mg after food, up to twice daily for 3 days. Review if fever persists beyond 48 hours." aria-label="Clinical notes"/><div className="composer-actions"><button className="primary-button" onClick={onSummary}><Icon name="sparkle"/>Create a simple care summary</button><span>Nothing is sent until you approve it</span></div>{summaryReady && <div className="generated-summary"><span><Icon name="check"/></span><div><strong>Here’s a draft for Ananya</strong><p>You may have a viral fever. Rest, drink plenty of fluids, and take paracetamol only as prescribed. Book a review if your fever continues for more than 48 hours.</p></div></div>}</section>
  </>;
}
function Metric({ value, label, detail, tone = "green" }: { value: string; label: string; detail: string; tone?: "green" | "orange" }) { return <article className="metric-card"><span className={`metric-indicator ${tone}`}/><div><strong>{value}</strong><span>{label}</span><small>{detail}</small></div></article>; }

function AdminDashboard({ leaveImpact, onLeave }: { leaveImpact: boolean; onLeave: () => void }) {
  return <><section className="health-ribbon"><div><span className="pulse-dot"/><strong>All core services operational</strong><small>Last checked 18 seconds ago</small></div><div className="service-stats"><span><strong>99.7%</strong>Email delivery</span><span><strong>100%</strong>Calendar sync</span><span><strong>0</strong>Failed jobs</span></div></section>
    <section className="admin-grid"><article className="card leave-card"><div className="card-head"><div><span className="section-kicker">Conflict-aware leave</span><h2>Doctor leave planner</h2></div><button className="primary-button compact" onClick={onLeave}><Icon name="plus"/>Mark leave</button></div><div className="leave-date"><span>AUG<strong>27</strong>THU</span><div><strong>Dr. Arjun Rao · Dermatology</strong><p>Leave requested · full day</p></div><StatusPill tone="orange">3 bookings affected</StatusPill></div>{leaveImpact ? <div className="impact-preview"><div><span><Icon name="check"/></span><div><strong>Safe leave workflow prepared</strong><p>3 appointments flagged, patients notified, alternatives ranked by specialty and time.</p></div></div><button>Review reassignment plan <Icon name="chevron" size={15}/></button></div> : <div className="impact-hint"><Icon name="shield" size={16}/><span>ArogyaFlow checks existing bookings before leave is committed.</span></div>}</article>
      <article className="card jobs-card"><div className="card-head"><div><span className="section-kicker">Reliable by design</span><h2>Notification queue</h2></div><StatusPill>Healthy</StatusPill></div><Job icon="@" title="Booking confirmations" detail="24 sent · 0 retrying" time="just now"/><Job icon="calendar" title="Calendar events" detail="18 synced · 0 pending" time="1m ago"/><Job icon="pill" title="Medication reminders" detail="41 delivered · 1 scheduled" time="2m ago"/><div className="retry-policy"><strong>Automatic recovery</strong><span>Exponential backoff · 5 attempts · dead-letter audit</span></div></article></section>
    <section className="section-block"><div className="section-title"><div><span className="section-kicker">Team availability</span><h2>Doctor profiles</h2></div><button className="secondary-button"><Icon name="plus"/>Add doctor</button></div><div className="doctor-table"><div className="table-head"><span>Doctor</span><span>Specialisation</span><span>Working hours</span><span>Slot</span><span>Status</span></div>{doctors.map((doctor, index) => <div className="table-row" key={doctor.id}><span className="table-doctor"><Avatar initials={doctor.initials} tone={doctor.color}/><strong>{doctor.name}</strong></span><span>{doctor.specialty}</span><span>{index === 2 ? "10:00 – 16:00" : "09:00 – 17:00"}</span><span>{index === 0 ? "30 min" : "45 min"}</span><StatusPill tone={index === 1 ? "orange" : "green"}>{index === 1 ? "Leave pending" : "Available"}</StatusPill></div>)}</div></section>
  </>;
}
function Job({ icon, title, detail, time }: { icon: "@" | "calendar" | "pill"; title: string; detail: string; time: string }) { return <div className="job-row"><span className={`job-icon ${icon === "@" ? "email" : icon}`}>{icon === "@" ? "@" : <Icon name={icon}/>}</span><div><strong>{title}</strong><span>{detail}</span></div><small>{time}</small></div>; }

function BookingPanel({ step, setStep, onClose, selectedDoctor, setSelectedDoctor, selectedSlot, setSelectedSlot, symptoms, setSymptoms, holdLabel, holdExpired, booked, onConfirm }: { step: number; setStep: (step: number) => void; onClose: () => void; selectedDoctor: typeof doctors[number]; setSelectedDoctor: (doctor: typeof doctors[number]) => void; selectedSlot: string; setSelectedSlot: (slot: string) => void; symptoms: string; setSymptoms: (value: string) => void; holdLabel: string; holdExpired: boolean; booked: boolean; onConfirm: () => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="booking-panel" role="dialog" aria-modal="true" aria-labelledby="booking-title"><header><div><span className="section-kicker">Let’s find you a time</span><h2 id="booking-title">{step === 1 ? "Who would you like to see?" : step === 2 ? "A few details before we book" : "You’re all set"}</h2></div><button onClick={onClose} aria-label="Close">×</button></header><div className="stepper"><span className={step >= 1 ? "active" : ""}>1</span><i/><span className={step >= 2 ? "active" : ""}>2</span><i/><span className={step >= 3 ? "active" : ""}>3</span></div>
    {step === 1 && <div className="booking-body"><label className="field-label">Available doctors</label><div className="doctor-options">{doctors.map((doctor) => <button key={doctor.id} className={selectedDoctor.id === doctor.id ? "selected" : ""} onClick={() => setSelectedDoctor(doctor)}><Avatar initials={doctor.initials} tone={doctor.color}/><span><strong>{doctor.name}</strong><small>{doctor.specialty} · {doctor.experience}</small></span><span className="radio-dot"/></button>)}</div><label className="field-label">Choose a time · Monday, 24 August</label><div className="slot-grid">{["09:30 AM", "10:30 AM", "11:15 AM", "02:15 PM", "03:00 PM"].map((slot) => <button className={selectedSlot === slot ? "selected" : ""} key={slot} onClick={() => setSelectedSlot(slot)}>{slot}</button>)}</div><div className="panel-footer"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => setStep(2)}>Hold this slot <Icon name="chevron" size={15}/></button></div></div>}
    {step === 2 && <div className="booking-body"><div className={`hold-banner ${holdExpired ? "expired" : ""}`}><Icon name="clock"/><span><strong>{holdExpired ? "We couldn’t keep this time open" : `We’ll keep this time for ${holdLabel}`}</strong><small>{holdExpired ? "Please choose the time once more." : "Take your time—nobody else can book it while you finish."}</small></span></div><div className="booking-summary"><Avatar initials={selectedDoctor.initials} tone={selectedDoctor.color}/><div><strong>{selectedDoctor.name}</strong><span>Mon, 24 Aug · {selectedSlot}</span></div></div><label className="field-label" htmlFor="symptoms">Tell the doctor what’s been bothering you</label><textarea id="symptoms" value={symptoms} onChange={(event) => setSymptoms(event.target.value)} placeholder="When did it start? What does it feel like? Is anything making it better or worse?"/><div className="ai-preview"><span><Icon name="sparkle"/></span><div><strong>A quick note for your doctor</strong><p>{symptoms.length > 25 ? "Headache with mild fever and tiredness. Your doctor may ask when it began and whether you have taken anything for it." : "A little more detail will help your doctor prepare."}</p><small>We only organise what you wrote—we never diagnose you.</small></div></div><div className="panel-footer"><button className="secondary-button" onClick={() => setStep(1)}>Back</button><button className="primary-button" disabled={holdExpired || symptoms.trim().length < 10} onClick={onConfirm}>Book my appointment <Icon name="check" size={15}/></button></div></div>}
    {step === 3 && <div className="booking-success"><span className="success-mark"><Icon name="check" size={28}/></span><h3>{booked ? "You’re booked!" : "Almost there"}</h3><p>{selectedDoctor.name} will see you then. We’ll send the details and keep both calendars updated if anything changes.</p><div><span><Icon name="calendar"/>Mon, 24 Aug</span><span><Icon name="clock"/>{selectedSlot}</span></div><button className="primary-button" onClick={onClose}>Back to my appointments</button></div>}
  </section></div>;
}
